DEBUG 2015-01-13 11:18:01,491: 	 Executing command: 'submit'
DEBUG 2015-01-13 11:18:01,492: 	 Found /afs/cern.ch/user/g/gcodispo/.crab3 file
DEBUG 2015-01-13 11:18:01,499: 	 Checking credentials
DEBUG 2015-01-13 11:18:01,499: 	 Found proxy file /tmp/x509up_u11551
DEBUG 2015-01-13 11:18:01,499: 	 Getting proxy life time left
DEBUG 2015-01-13 11:18:01,902: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11551 -timeleft
 output : 86252

 error: 
 retcode : 0
DEBUG 2015-01-13 11:18:02,307: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11551 -actimeleft
 output : 86251

 error: 
 retcode : 0
DEBUG 2015-01-13 11:18:02,307: 	 Proxy valid for 23:57:32 hours
INFO 2015-01-13 11:18:02,307: 	 Will use configuration file crab3_particleGunGenSim_MuMinus.py~
DEBUG 2015-01-13 11:18:02,307: 	 Loading configuration
ERROR: ImportError: No module named crab3_particleGunGenSim_MuMinus~

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: 3.3.12.patch1
Unhandled Exception!
No module named crab3_particleGunGenSim_MuMinus~
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 218, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/WMCore/Configuration.py", line 549, in loadConfigurationFile
    modPath = imp.find_module(cfgBaseName, [cfgDirName])
ImportError: No module named crab3_particleGunGenSim_MuMinus~
	Please use crab uploadlog to upload the log file /afs/cern.ch/user/g/gcodispo/scratch1/CMSSW_7_2_3_patch1/src/L1Trigger/L1IntegratedMuonTrigger/test/crab3/crab.log
DEBUG 2015-01-13 11:18:10,190: 	 Executing command: 'submit'
DEBUG 2015-01-13 11:18:10,191: 	 Found /afs/cern.ch/user/g/gcodispo/.crab3 file
DEBUG 2015-01-13 11:18:10,195: 	 Checking credentials
DEBUG 2015-01-13 11:18:10,196: 	 Found proxy file /tmp/x509up_u11551
DEBUG 2015-01-13 11:18:10,196: 	 Getting proxy life time left
DEBUG 2015-01-13 11:18:10,598: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11551 -timeleft
 output : 86243

 error: 
 retcode : 0
DEBUG 2015-01-13 11:18:11,002: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11551 -actimeleft
 output : 86243

 error: 
 retcode : 0
DEBUG 2015-01-13 11:18:11,002: 	 Proxy valid for 23:57:23 hours
INFO 2015-01-13 11:18:11,003: 	 Will use configuration file crab3_particleGunGenSim_MuPlus.py~
DEBUG 2015-01-13 11:18:11,003: 	 Loading configuration
ERROR: ImportError: No module named crab3_particleGunGenSim_MuPlus~

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: 3.3.12.patch1
Unhandled Exception!
No module named crab3_particleGunGenSim_MuPlus~
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 218, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 46, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/WMCore/Configuration.py", line 549, in loadConfigurationFile
    modPath = imp.find_module(cfgBaseName, [cfgDirName])
ImportError: No module named crab3_particleGunGenSim_MuPlus~
	Please use crab uploadlog to upload the log file /afs/cern.ch/user/g/gcodispo/scratch1/CMSSW_7_2_3_patch1/src/L1Trigger/L1IntegratedMuonTrigger/test/crab3/crab.log
DEBUG 2015-01-13 11:23:25,123: 	 Executing command: 'status'
DEBUG 2015-01-13 11:23:25,124: 	 Found /afs/cern.ch/user/g/gcodispo/.crab3 file
DEBUG 2015-01-13 11:23:25,134: 	 Checking credentials
DEBUG 2015-01-13 11:23:25,134: 	 Found proxy file /tmp/x509up_u11551
DEBUG 2015-01-13 11:23:25,134: 	 Getting proxy life time left
DEBUG 2015-01-13 11:23:25,637: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11551 -timeleft
 output : 85928

 error: 
 retcode : 0
DEBUG 2015-01-13 11:23:26,041: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11551 -actimeleft
 output : 85927

 error: 
 retcode : 0
DEBUG 2015-01-13 11:23:26,041: 	 Proxy valid for 23:52:08 hours
ERROR 2015-01-13 11:23:26,042: 	 Cannot find .requestcache file inside the working directory for task crab_particleGunGenSim_MuMinus_v1
ERROR 2015-01-13 11:23:26,043: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 242, in __init__
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 346, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/client_utilities.py", line 389, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file inside the working directory for task crab_particleGunGenSim_MuMinus_v1
DEBUG 2015-01-13 11:24:41,112: 	 Executing command: 'status'
DEBUG 2015-01-13 11:24:41,112: 	 Found /afs/cern.ch/user/g/gcodispo/.crab3 file
DEBUG 2015-01-13 11:24:41,120: 	 Checking credentials
DEBUG 2015-01-13 11:24:41,121: 	 Found proxy file /tmp/x509up_u11551
DEBUG 2015-01-13 11:24:41,121: 	 Getting proxy life time left
DEBUG 2015-01-13 11:24:41,626: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11551 -timeleft
 output : 85852

 error: 
 retcode : 0
DEBUG 2015-01-13 11:24:42,032: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11551 -actimeleft
 output : 85851

 error: 
 retcode : 0
DEBUG 2015-01-13 11:24:42,033: 	 Proxy valid for 23:50:52 hours
ERROR 2015-01-13 11:24:42,040: 	 Cannot find .requestcache file inside the working directory for task crab_particleGunGenSim_MuPlus_v1
ERROR 2015-01-13 11:24:42,040: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 242, in __init__
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 346, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/client_utilities.py", line 389, in loadCache
    raise CachefileNotFoundException(msg)
CachefileNotFoundException: Cannot find .requestcache file inside the working directory for task crab_particleGunGenSim_MuPlus_v1
DEBUG 2015-01-13 11:32:28,781: 	 Executing command: 'submit'
DEBUG 2015-01-13 11:32:28,782: 	 Found /afs/cern.ch/user/g/gcodispo/.crab3 file
DEBUG 2015-01-13 11:32:28,791: 	 Checking credentials
DEBUG 2015-01-13 11:32:28,792: 	 Found proxy file /tmp/x509up_u11551
DEBUG 2015-01-13 11:32:28,792: 	 Getting proxy life time left
DEBUG 2015-01-13 11:32:29,296: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11551 -timeleft
 output : 85384

 error: 
 retcode : 0
DEBUG 2015-01-13 11:32:29,699: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u11551 -actimeleft
 output : 85384

 error: 
 retcode : 0
DEBUG 2015-01-13 11:32:29,699: 	 Proxy valid for 23:43:04 hours
INFO 2015-01-13 11:32:29,699: 	 Will use configuration file crab3_L1ITMuonBarrelLocalTrigger_50ns.py
DEBUG 2015-01-13 11:32:29,699: 	 Loading configuration
ERROR 2015-01-13 11:32:29,700: 	 Working area '/afs/cern.ch/user/g/gcodispo/scratch1/CMSSW_7_2_3_patch1/src/L1Trigger/L1IntegratedMuonTrigger/test/crab3/MBPrimitivesProduction/crab_Neutrino_Pt-2to20_gun-AVE30BX50_v1' already exists 
Please change the requestName in the config file
ERROR 2015-01-13 11:32:29,700: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/submit.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args = True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 222, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.12.patch1/lib/python2.6/site-packages/CRABClient/client_utilities.py", line 336, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/g/gcodispo/scratch1/CMSSW_7_2_3_patch1/src/L1Trigger/L1IntegratedMuonTrigger/test/crab3/MBPrimitivesProduction/crab_Neutrino_Pt-2to20_gun-AVE30BX50_v1' already exists 
Please change the requestName in the config file
